extends: semistandard
env:
  browser: true
  commonjs: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Phaser: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-console:
    - warn
    - allow:
      - table
